# Generated by Django 4.2.4 on 2023-09-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocuments',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
